spring:
  redis:
    host: 13.125.19.213
    password: 1234
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/user?useSSL=false&allowMultiQueries=true&serverTimezone=UTC"
    username: root
    password: 1234


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.125.19.213:8761/eureka
