server:
  port: 9091

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  profiles:
    include: prod
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 1234
  application:
    name: user-service

  security:
    oauth2:
      client:
        registration:
          naver:
            scope: email,nickname,gender,mobile
            authorization-grant-type: authorization_code
            client-secret: ZLCkJYhudO
            client-id: DlmIo1AnHsg_vbhA10Uq
            redirect_uri: 'http://localhost:9091/login/oauth2/code/naver'
            client-name: Naver

          kakao:
            authorization-grant-type: authorization_code
            client-id: e609a9228951a646dcd084d17750e261
            client-secret: g19bIu9gSbNOUOEAE7AdTGOCawwYSKQ2
            scope: profile_nickname, account_email
            client-authentication-method: POST
            redirect-uri: 'http://localhost:9091/login/oauth2/code/kakao'
            client-name: kakao

          google:
            scope: profile, email
            client-id: 974264929560-46jc5bmg2s54u18vcpr649c231jc4c4b.apps.googleusercontent.com
            client-secret: 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

        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
    show_sql: false
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#token:
#  expiration_time: 864000000
#  secret: 'iuyweiukfyuewkifuewikfuweikfuewikfuwekifuewik'

springdoc:
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  version: v1.0.0
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /bus/v3/api-docs
  cache:
    disabled: true
  packages-to-scan: com.nanum

cloud:
  aws:
    credentials:
      accessKey: AKIA4CDIXXFFKCY4FC7K
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'

sms:
  senderPhone: '01046447221'
  serviceId: 'ncp:sms:kr:293418085250:nanum-sms'
  accessKey: 'I7wL0G67VkWWSsQo1YJV'
  secretKey: 'DFziahn2T1xgHLFyjGR78gmGc57QuwdTc5Wk1cAX'