spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://user-service-db.chggg0w4gyxa.ap-northeast-2.rds.amazonaws.com/userDB?serverTimezone=Asia/Seoul"
    username: nanum
    password: spharos1234!