spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-service.mysql.database.azure.com/userDB?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: nanum
    password: spharos1234!

  redis:
    host: nanum-redis.redis.cache.windows.net
    password: BDAMHPDXwVE1lmSGjYHPNOuZBE23xHXLqAzCaGLPsIU=
    port: 6380
    ssl: true

#    #    타임 아웃 설정 필수
#    hik
#    ari:
#      idle-timeout: 100000
#      max-lifetime: 580000
#      connection-timeout: 10000
#      validation-timeout: 10000

  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 20.214.170.222
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://20.214.170.222:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health